// Package server — font_meta_load.go
//
// Loads the pre-computed font cmap JSON (extracted by scripts/
// extract-font-cmaps.py) and embeds it for runtime use. The JSON
// lives in testdata/fontcmaps.json because it can be regenerated
// from the woff2 files and doesn't need to be edited by hand.
//
// Why embed-as-JSON rather than parse the woff2 at runtime:
//   - No brotli dependency in Go (the data pipeline already has
//     fonttools + brotli for Python).
//   - The cmap is read once at startup and never changes.
//   - The Go server doesn't need to know the woff2 format at all.
package server

import (
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
)

// fontcmapsJSON is generated by scripts/extract-font-cmaps.py from
// backend/fonts/{hafs,AmiriQuran-Regular}.woff2. Re-run the script
// after changing either font.
//
//go:embed testdata/fontcmaps.json
var fontcmapsJSON []byte

// loadFontCMaps parses the embedded fontcmaps.json and returns two
// codepoint→glyph-name maps (one per font). The keys are runes
// (parsed from 4-digit lowercase hex strings in the JSON).
func loadFontCMaps() (hafs, amiri map[rune]string, err error) {
	hafs = make(map[rune]string)
	amiri = make(map[rune]string)

	var raw struct {
		Hafs       map[string]string `json:"hafs"`
		AmiriQuran map[string]string `json:"amiriquran"`
	}
	if err := json.Unmarshal(fontcmapsJSON, &raw); err != nil {
		return nil, nil, fmt.Errorf("parse fontcmaps.json: %w", err)
	}

	hexToRune := func(s string) (rune, error) {
		b, err := hex.DecodeString(s)
		if err != nil {
			return 0, fmt.Errorf("bad hex %q: %w", s, err)
		}
		if len(b) < 2 || len(b) > 4 {
			// WOFF2 fonts we use are BMP-only (no surrogate pairs),
			// so a single BMP rune (1-3 bytes) covers everything.
			return 0, fmt.Errorf("unexpected rune width %d bytes for %q", len(b), s)
		}
		var cp uint32
		for _, b1 := range b {
			cp = cp<<8 | uint32(b1)
		}
		return rune(cp), nil
	}

	for k, v := range raw.Hafs {
		r, err := hexToRune(k)
		if err != nil {
			return nil, nil, fmt.Errorf("hafs cmap key %q: %w", k, err)
		}
		hafs[r] = v
	}
	for k, v := range raw.AmiriQuran {
		r, err := hexToRune(k)
		if err != nil {
			return nil, nil, fmt.Errorf("amiri cmap key %q: %w", k, err)
		}
		amiri[r] = v
	}
	return hafs, amiri, nil
}
